// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBazktfCgVqLKF5Fn6s0GeYvpZSb7k6LY',
    appId: '1:1077112537407:web:e6ab6c7a1952b1732a938a',
    messagingSenderId: '1077112537407',
    projectId: 'coba-88489',
    authDomain: 'coba-88489.firebaseapp.com',
    databaseURL: 'https://coba-88489-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coba-88489.appspot.com',
    measurementId: 'G-WX83SF6RMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe27RUGXbqsRj6HvlJFnb1j1R1e3q9tP4',
    appId: '1:1077112537407:android:5ce770ccc626276d2a938a',
    messagingSenderId: '1077112537407',
    projectId: 'coba-88489',
    databaseURL: 'https://coba-88489-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coba-88489.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_NmQpS6cUajRRI7acojREksI6J35yZBo',
    appId: '1:1077112537407:ios:c726b8ba6014e3b02a938a',
    messagingSenderId: '1077112537407',
    projectId: 'coba-88489',
    databaseURL: 'https://coba-88489-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coba-88489.appspot.com',
    iosClientId: '1077112537407-uh0sf4e8iamrvhtegqo35mrn5fc4haco.apps.googleusercontent.com',
    iosBundleId: 'com.example.wisataApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBazktfCgVqLKF5Fn6s0GeYvpZSb7k6LY',
    appId: '1:1077112537407:web:3aefc433f348ab862a938a',
    messagingSenderId: '1077112537407',
    projectId: 'coba-88489',
    authDomain: 'coba-88489.firebaseapp.com',
    databaseURL: 'https://coba-88489-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coba-88489.appspot.com',
    measurementId: 'G-YTR30HFFSP',
  );
}
